src/__test__/ModalWrapper.test.tsx
src/components/ModalWrapper.tsx

공통컴포넌트 ModalWrapper 컴포넌트 구현 풀리퀘스트 입니다.
1. ModalWrapper컴포넌트 생성
2. ModalWrapper테스트코드작성
프롭스는 최소화 하려했고. 지정된 프롭스를 다루어 모달을 사용하면 됩니다.
특이 사항
fixed속성을 이용해서 구현하였기에 다른 postition속성(relative,absolute 등)이 형제태그로 들어왔을때 겹쳐지는 이슈가 생겨 z-index를 불가피하게 사용하였습니다 참고하여 사용 부탁드리겠습니다.

Feat: ModalWrapper 공통컴포넌트 생성 풀리퀘스트

---

src/components/Footer/Footer.tsx
src/components/Header/Navbar.tsx

코드리뷰 받은 요청 사항 수정해서 적용했습니다.
1. Footer의 Link style -> tailwind 적용
2. Navbar의 이미지 next/image 프로퍼티 적용

Refactor: 코드리뷰 수정 사항

---

src/app/classroom/page.tsx
src/app/community/page.tsx
src/components/Community/Aside/Aside.tsx
src/components/Community/CommunityCard.tsx
src/components/Community/CommunityList.tsx
src/components/Header/Navbar.tsx
src/components/Header/Tab.tsx
src/components/password/ForgotPassword.tsx
src/hooks/reactQuery/useGetSelectedPost.tsx

`어떤 이유에서 이 PR을 시작하게 됐는지에 대한 히스토리를 남겨주세요.`
`이슈 번호를 적어주세요. 해당 PR이 merge되면 닫히는 이슈는 close를 붙여주세요./해당 이슈사항을 해결하기 위해 어떤 작업을 했는지 남겨주세요.`
`ex) close #8 로그인 페이지 버튼 `
`리뷰하는 사람이 어떻게 테스트할 수 있을지 간략히 써주세요.`

Team10 feat/community style

---

src/components/ModalWrapper.tsx

ModalWrapper 컴포넌트를 Confirm 모달에도 적용하기 위해 props를 수정했습니다.

Update: ModalWrapper props 추가

---

src/components/Community/CommunityCard.tsx
src/hooks/reactQuery/community/useDeletePost.tsx

Feat: 게시글 삭제 기능

---

src/app/assignment/(components)/(submittedAssignment)/SubmittedAssignment.tsx
src/utils/downloadAssignmentFile.ts

제출된 과제 파일 다운로드 기능 추가
- downloadAssignmentFile util 함수 추가
- 제출된 과제 파일명 클릭 시 제출된 과제 파일 다운로드 기능 추가
- 관련 Issue: close #28

Feat: 제출된 과제 파일 다운로드 기능 추가

---

src/app/classroom/(components)/CreateLecture.tsx
src/app/classroom/(components)/CreateLectureMethod.tsx
src/app/classroom/(components)/LectureNote.tsx

ModalWrapper 공통 컴포넌트 수정에 의한 onCloseModal props 수정 및 디자인 너비 값 수정
- ModalWrapper 공통 컴포넌트 props 이름이 handleModal > onCloseModal 로 수정
- width값이 적용되지 않아 LectureMethod, LectureNote 컴포넌트 width값 지정

Fix: ModalWrapper 수정에 따른 props, style 수정

---

src/app/classroom/(components)/ClassroomSidebar.tsx
src/app/classroom/(components)/CourseSection.tsx
src/app/classroom/(components)/LectureItem.tsx
src/app/classroom/(components)/LectureList.tsx
src/app/classroom/page.tsx

클릭한 섹션의 강의리스트 화며에 렌더링 작업
- 강의리스트를 받아오는 컴포넌트에 섹션을 클릭 했을 시, id 값을 받아오는 값을 연결하여
- 클릭한 섹션에 대한 하위 강의 리스트를 렌더링 하도록 작업했습니다.

Team4 feat 사이드바 강의장 연결

---

src/app/assignment/(components)/(feedback)/Feedback.tsx
src/app/assignment/(components)/(feedback)/FeedbackCardSkeleton.tsx
src/app/assignment/(components)/AssignmentDetail.tsx
src/hooks/reactQuery/feedback/useGetFeedbacks.tsx
src/hooks/reactQuery/feedback/useMutateFeedback.tsx

피드백 데이터 prefetch 기능 추가
- 피드백 데이터를 미리 불러오기 위하여 prefetch를 hook에 추가했습니다.
- 피드백 데이터를 불러오기 전에 보여줄 skeleton을 추가하였습니다. (둘 중의 하나만 사용하여, 추후 하나는 삭제될 예정)
- 수정, 삭제 시의 완료 alret문을 추가하였습니다.
- #101 
- #27 
- #23 
- #21

Team8 피드백 prefetch 기능 추가

---

src/components/Community/Aside/Aside.tsx
src/components/Community/CommunityCard.tsx
src/components/Community/CommunityList.tsx
src/components/Community/Layout.tsx
src/components/Community/PostForm/PostForm.tsx
src/components/Community/PostForm/PostTags.tsx
src/components/Community/PostForm/SelectMenu.tsx
src/components/CommunityModal/CommunityModal.tsx
src/components/common/Button.tsx
src/components/common/ImageUploader.tsx
src/hooks/reactQuery/comment/useCreateComment.ts
src/utils/deleteStorageImages.ts
src/utils/imageCompress.ts
src/utils/uploadStorageImages.ts

Fix: 커뮤니티 페이지 글 수정 기능 구현 풀리퀘스트입니다.
* 썸네일 이미지 스토리지에 올라가지 않는 이슈해결
*  태그 삭제 기능 추가
* 기존 이미지 삭제 시 스토리지에서 삭제
* 추가된 이미지일 경우에만 스토리지에 저장
* 글 수정 클릭 시 바로 내용 띄우기
* 글 수정 클릭 시 기존 선택된 카테고리 및 이미지 띄우기

Fix: community update post

---

src/app/assignment/(components)/(assignmentCreateModal)/FileUploader.tsx
src/app/assignment/(components)/(assignmentCreateModal)/Modal.tsx
src/app/assignment/(components)/(assignmentlist)/AssignmentCard.tsx
src/app/assignment/(components)/(assignmentlist)/AssignmentListBox.tsx
src/app/assignment/(components)/(assignmentlist)/AssignmentRoleCheck.tsx
src/app/assignment/(components)/(assignmentlist)/AssignmentSidebarButtons.tsx
src/app/assignment/(components)/(submittedAssignment)/SubmittedAssignment.tsx
src/app/assignment/(components)/AssignmentSidebar.tsx
src/app/assignment/[assignmentId]/(assignmentDetail)/Detail.tsx
src/app/assignment/[assignmentId]/(assignmentDetail)/Main.tsx
src/app/assignment/[assignmentId]/(assignmentDetail)/SubmitAssignmentCard.tsx
src/app/assignment/[assignmentId]/(assignmentDetail)/SubmittedAssignmentList.tsx
src/app/assignment/page.tsx
src/hooks/reactQuery/assignment/useGetSubmitted.tsx
src/hooks/reactQuery/submittedAssignment/useGetSubmittedAssignment.ts

Feature 에서 작업한 내용들을 하나로 합치기 위한 일
- Main, Detail페이지 각 feature 연결 작업

Team8 refactor/combinefeature

---

src/components/RequireAuth/RequireAuth.tsx

assignment, mypage, classroom 등 페이지에서 새로고침시 community 페이지로 redirect되는 문제를 고쳤습니다.
close #146

Fix: Redirect 오류 해결

---

src/app/assignment/(components)/(assignmentCreateModal)/DatePicker.tsx
src/app/assignment/(components)/(assignmentCreateModal)/Modal.tsx

(긴급) 과제 모달 코드 수정
- setValue 함수 과제 모달에서 주석 처리함

Feat: 과제 모달 수정

---

src/app/mypage/(components)/Progress.tsx

Team10 feat/mypage progress

---

src/app/mypage/page.tsx
src/components/Community/CommunityCard.tsx
src/components/Community/Inputbar.tsx
src/components/Community/PostForm/PostForm.tsx
src/components/CommunityModal/CommentCard.tsx
src/components/CommunityModal/CommentInput.tsx
src/components/CommunityModal/PostCard.tsx
src/components/Header/Navbar.tsx
src/hooks/reactQuery/useGetProgressQuery.tsx

Team10 feat/mypage error

---

src/app/assignment/(components)/(assignmentlist)/AssignmentCard.tsx
src/app/assignment/(components)/(assignmentlist)/AssignmentListBox.tsx
src/app/assignment/(components)/(assignmentlist)/AssignmentRoleCheck.tsx
src/app/assignment/(components)/(assignmentlist)/AssignmentSidebarButtons.tsx
src/app/assignment/(components)/AssignmentSidebar.tsx
src/hooks/reactQuery/assignment/useGetCurrentStudentSubmittedAssignments.tsx

유저 role에따른 분기처리 기능 개발
1. 사이드바 분기처리
2. 리스트분기처리
3. 수강생일때 그수강생의 서미티드어사인먼트 리스트 가져오는훅생성

Feat: 과제 롤분기처리

---

package-lock.json
package.json
src/app/assignment/(components)/(assignmentCreateModal)/DatePicker.tsx
src/app/assignment/(components)/(assignmentCreateModal)/FileUploader.tsx
src/app/assignment/(components)/(assignmentCreateModal)/Modal.tsx
src/app/assignment/[assignmentId]/(assignmentDetail)/Main.tsx
src/app/assignment/[assignmentId]/(assignmentDetail)/SubmitAssignmentCard.tsx
src/app/assignment/[assignmentId]/(assignmentDetail)/SubmittedAssignmentList.tsx
src/hooks/reactQuery/assignment/useCreateAssignment .tsx
src/hooks/reactQuery/assignment/useUpdateAssignment .tsx
src/hooks/reactQuery/submittedAssignment/useGetSubmittedAssignment.ts
yarn.lock

과제 모달을 위한 수정,생성 기능 추가
- useCreateAssignment.tsx, useUpdateAssignment.tsx 과제 모달 생성,수정을 위한 커스텀 훅 개발
- 데이트 픽커 및 파일 업로드 기능 수정

Team8 feat/assignmentdetailpage

---

src/app/assignment/(components)/(feedback)/FeedbackCard.tsx
src/app/assignment/(components)/(feedback)/FeedbackTextArea.tsx
src/app/assignment/(components)/(feedback)/VerificationModal.tsx

피드백 코드 리팩토링
- 피드백의 프로필 이미지가 기본 이미지, 로그인한 유저, 등록된 유저 정보에 따라 변동되어도 사이즈가 동일하도록 수정하였습니다.
- 피드백 textarea 컴포넌트의 코드를 리팩토링하였습니다.
- #168

Team8 refactor/feedback

---

src/app/assignment/(components)/AssignmentLinkSubmitModal.tsx
src/app/assignment/(components)/StudentAssignmentSubmitCard.tsx
src/app/assignment/[assignmentId]/(assignmentDetail)/SubmittedAssignmentList.tsx
src/hooks/common/useModal.tsx
src/hooks/reactQuery/submittedAssignment/useGetSubmittedAssignementId.ts

수강생 사용자 과제 제출 시 카드 컴포넌트에 제출 완료 표시, 제출 내용 확인 모달 open 기능 추가 및 일부 기능 수정
- 수강생 사용자 과제 제출 시 카드 컴포넌트에 제출 완료 표시, 제출 내용 확인 모달 open 기능 추가
- 과제 링크 제출 모달 내 업로드 버튼 클릭 시 input에 입력된 값 유효성 검사 및 제출 기능 추가 
(변경 전: links 배열에 담긴 값만 제출 -> 변경 후: links 배열에 담긴 값 및 input에 입력된 값 함께 제출)
- useGetSubmittedAssignmentId hook 추가
- useModal hook 추가
- 관련 Issues
close #29

Team8 feat/assignment submission

---

src/components/LoginForm/LoginForm.tsx
src/components/password/ForgotPassword.tsx
src/hooks/reactQuery/login/useFindPassword.ts
src/hooks/reactQuery/login/useLoginMutation.ts
src/hooks/useToast.ts

Toast Hook을 Hooks에 추가함. 추후 재사용성을 고려한다면 코드가 수정될 필요가 있음.
close #179

Feat: Toast 추가

---

src/app/assignment/(components)/AssignmentSidebar.tsx
src/hooks/reactQuery/assignment/useCreateAssignment .tsx
src/hooks/reactQuery/assignment/useDeleteAssignments.tsx

과제 삭제 & 수정 기능 수정
1. 과제 삭제시 order값 변경이 필요해 로직추가하면서 useDeleteAssignments훅 리팩토링
2. 과제생성시 order값 설정 변경 (+1제거)
3. 사이드바 프롭스 추가 (4팀에서 변경예정코드 전달받아서 추가해놓음)

Team8 fix 과제 삭제 로직 수정 및 생성order값변경

---

src/app/assignment/(components)/(submittedAssignment)/SubmittedAssignmentContent.tsx
src/app/assignment/(components)/AssignmentFileSubmitModal.tsx
src/app/assignment/(components)/AssignmentLinkSubmitModal.tsx
src/app/assignment/(components)/StudentAssignmentSubmitCard.tsx
src/app/assignment/(components)/SubmittedAssignmentDetail.tsx
src/hooks/reactQuery/submittedAssignment/useDeleteSubmittedAssignment.ts

- 제출된 과제를 삭제할 수 있는 기능 추가(피드백이 작성되지 않은 상태에서만 삭제 가능)
- 수강생이 본인이 제출한 과제를 삭제할 수 있는 기능 추가(피드백이 작성되지 않은 상태에서만 삭제 가능)
- 과제 링크/파일 업로드 후 과제 제출 상태 확인 refetch 기능 추가
- 과제 삭제 기능 구현을 위한 useDeleteSubmittedAssignment hook 추가
- 관련 Issues
close #31

Feat: 제출된 과제 삭제 기능 추가

---

src/components/Sidebar.tsx

과제사이드바 링크이동을위한 sidebar 공통컴포넌트수정
1. 파라미터를 이용해 어사인먼트페이지이고 어사인먼트아이디 파라미터를 이용해 링크이동기능과 스타일링변경되도록 기능수정

Fix: 과제사이드바 링크이동을위한 sidebar 공통컴포넌트수정

---

src/hooks/reactQuery/assignment/useUpdateAssignment .tsx

Feat: 과제 모달 살짝 수정

---

src/app/classroom/(components)/LectureItem.tsx

Fix: 강의장  오타 수정
